### ISSUE TITLE
Install problem in Anaconda 5.2

### ISSUE THREAD

**Issue by juliotux** [astroconda/astroconda-iraf#4] opened 2018-09-17 20:36 UTC
Hello Astroconda team,
When I try to install iraf in Anaconda 5.2, the following error rises during the installation.

```
Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(502): An error occurred while installing package 'http://ssb.stsci.edu/astroconda::iraf.adccdrom-2013_01_02-1'.
LinkError: post-link script failed for package http://ssb.stsci.edu/astroconda::iraf.adccdrom-2013_01_02-1
running your command again with `-v` will provide additional information
location of failed script: /home/julio/.anaconda3/bin/.iraf.adccdrom-post-link.sh
==> script messages <==
<None>

Attempting to roll back.

Rolling back transaction: done

LinkError: post-link script failed for package http://ssb.stsci.edu/astroconda::iraf.adccdrom-2013_01_02-1
running your command again with `-v` will provide additional information
location of failed script: /home/julio/.anaconda3/bin/.iraf.adccdrom-post-link.sh
==> script messages <==
<None>
```

The same problem was also reported by another user in [Anaconda forum](https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/h7TkH9aJoNs).

**Comment by juliotux** [comment] 2019-01-19 18:04
Problem identified: Conda env has an empty `$PREFIX` variable, instead, the true prefix is exported in `CONDA_PREFIX` variable. Possible solution in #5 pull request.

**Comment by jehturner** [comment] 2019-03-20 15:54
Thanks for submitting this (especially the PR) and sorry I hadn't spotted it earlier. I believe, however, that the use of PREFIX in post-install scripts came straight from the conda-build documentation and should be working. Remember that these "-post-link.sh" files get executed via conda, not directly. Otherwise, I don't believe PREFIX would *ever* have worked. The original link to the applicable conda-build page is now broken, but you can find PREFIX mentioned in a newer version at https://docs.conda.io/projects/conda-build/en/stable/source/link-scripts.html. We do unavoidably stretch those overly-restrictive guidelines, but that's a separate issue... I think it's not correct to substitute CONDA_PREFIX, because that relies on external information rather than the intended interface and, more importantly, CONDA_PREFIX is not necessarily the environment you are installing into, it's the one you currently have active (eg. `base`), so this solution won't always work.

Could you please confirm what OS release the above error ocurrs on, the output from `conda list` in the environment from which you try (and fail) to run `conda install/create` and the output of `/usr/bin/python --version`, to see if I can reproduce the problem or figure out what's different from my working Anaconda 5.2 install? Could you also just double check that one of the original AstroConda IRAF packages is still failing to install there? Is there any chance that changing PREFIX is not actually what resolved your problem, given that it is working for me and the error you reported looks like a different known problem? Thanks.

**Comment by juliotux** [comment] 2019-03-21 01:57
I put all outputs of `iraf-all` in this [gist](https://gist.github.com/juliotux/aad5526e857a9cfbd93216ab1e8fa1f4)

About the OS: I use Arch Linux.

This problem only appear when installing packages with -post-link.sh. IRAF itself do not suffer from this problem and can be installed whitout errors.

edit: Problem persists even if conda is updated.

**Comment by jehturner** [comment] 2019-03-21 16:03
Thanks. I believe I know what's going on here; we need to fix `ac_update_extern_pkg` to work properly on your OS Python 3.7 (which we use due to all the constraints/assumptions mentioned in the above `conda-build` docs). This has been reported before and I'm going to have a look at it.

**Comment by jhunkeler** [comment] 2019-04-03 04:31
Linking #6

**Comment by jehturner** [comment] 2019-04-03 20:37
I have a new set of package builds that I hope will resolve this. Would you mind adding the channel http://astroconda.gemini.edu/testing and trying the installation (into some test env) again? Thanks. You might want to remove that channel afterwards so you don't pick up test versions in future.

**Comment by juliotux** [comment] 2019-04-03 21:11
Hello @jehturner, now everything look to work fine. I could install `iraf-all` packages without problem and run iraf. Just another bug found, in `mkiraf`, that will be submited in another issue. Thanks.

**Comment by jehturner** [comment] 2019-04-03 21:22
Great. I'll close this once the packages are in the main channel (they are fine in my testing, but we could wait a few days for possible confirmation from 1-2 other users).

**Comment by PotionSell** [comment] 2019-06-06 23:29
I had the same problem while building a new PyRAF/IRAF astroconda environment. I added the gemini testing channel as @jehturner suggested and the problem was resolved. Will these test changes be live in a future update?

**Comment by jehturner** [comment] 2019-06-07 00:26
Yes, sorry, I'll get the new builds moved there.

**Comment by jehturner** [comment] 2023-04-13 22:46
This should have been closed when the new packages were published.

**Closed as completed by jehturner** 2023-04-13 22:46 UTC
